#!/usr/bin/env python3
"""Seed the dummy Canary=Control / Canary=Experiment series into VictoriaMetrics.

Writes two metrics (dummy_latency, dummy_error_rate), each with a baseline
series (Canary="Control") and a canary series (Canary="Experiment"), over a
fixed recent window, via VM's Prometheus text import endpoint
(POST /api/v1/import/prometheus). Idempotent: re-running overwrites the same
(series, timestamp) points.

Each series carries just the `Canary` label (plus the metric name), so the
canary-config template metric{Canary="${scope}"} selects exactly one series per
scope.

Deliberately trivial dummy data for the model-free wiring/regression check. The
labelled evaluation dataset used for the scored experiment is generated by
tools/eval_dataset.py (same Canary scheme).

Usage:
    python tools/seed_dummy_data.py [--vm-url http://localhost:8428]
                                    [--window-mins 30] [--step 60]
"""

from __future__ import annotations

import argparse
import math
import sys
import time
from typing import Dict, List

import requests

# Window/shape constants. The pipeline requests a window strictly inside this
# seeded range (see tools/run_pipeline.py SEED_WINDOW_MINS vs ANALYSIS_*).
DEFAULT_WINDOW_MINS = 30
DEFAULT_STEP_SECONDS = 60

# Per-metric baseline level and the experiment shift (experiment is modestly
# higher so the judges have a non-trivial (but not extreme) signal to score).
METRICS = {
    "dummy_latency": {"control_base": 100.0, "experiment_factor": 1.12, "amplitude": 4.0},
    "dummy_error_rate": {"control_base": 1.0, "experiment_factor": 1.20, "amplitude": 0.1},
}


def _value(base: float, amplitude: float, i: int, factor: float = 1.0) -> float:
    """Deterministic, gently-varying value (sine ripple), reproducible, no RNG."""
    return round((base + amplitude * math.sin(i / 3.0)) * factor, 4)


def build_payload(window_mins: int, step: int) -> str:
    now = int(time.time())
    now -= now % step  # align to step boundary
    start = now - window_mins * 60
    timestamps = list(range(start, now + 1, step))

    lines: List[str] = []
    for metric, cfg in METRICS.items():
        for i, ts in enumerate(timestamps):
            ts_ms = ts * 1000
            control = _value(cfg["control_base"], cfg["amplitude"], i)
            experiment = _value(
                cfg["control_base"], cfg["amplitude"], i, factor=cfg["experiment_factor"]
            )
            lines.append(f'{metric}{{Canary="Control"}} {control} {ts_ms}')
            lines.append(f'{metric}{{Canary="Experiment"}} {experiment} {ts_ms}')
    return "\n".join(lines) + "\n"


def seed(vm_url: str, window_mins: int, step: int) -> int:
    payload = build_payload(window_mins, step)
    n_points = payload.count("\n")
    import_url = f"{vm_url.rstrip('/')}/api/v1/import/prometheus"
    resp = requests.post(import_url, data=payload.encode("utf-8"), timeout=30)
    resp.raise_for_status()
    # VM import is async-flushed; force a flush so points are queryable promptly.
    try:
        requests.get(f"{vm_url.rstrip('/')}/internal/force_flush", timeout=10)
    except requests.RequestException:
        pass
    print(f"[seed] imported {n_points} samples into {import_url}")
    return n_points


def verify(vm_url: str, window_mins: int, step: int) -> bool:
    """Read back both scopes for dummy_latency via query_range."""
    now = int(time.time())
    start = now - (window_mins + 2) * 60
    ok = True
    for scope in ("Control", "Experiment"):
        params = {
            "query": f'dummy_latency{{Canary="{scope}"}}',
            "start": start,
            "end": now,
            "step": step,
        }
        r = requests.get(f"{vm_url.rstrip('/')}/api/v1/query_range", params=params, timeout=15)
        r.raise_for_status()
        data = r.json()
        results = data.get("data", {}).get("result", [])
        n = len(results[0]["values"]) if results else 0
        print(f"[seed] verify dummy_latency Canary={scope}: {n} points")
        ok = ok and n > 0
    return ok


def main() -> int:
    ap = argparse.ArgumentParser(description="Seed dummy canary data into VictoriaMetrics")
    ap.add_argument("--vm-url", default="http://localhost:8428")
    ap.add_argument("--window-mins", type=int, default=DEFAULT_WINDOW_MINS)
    ap.add_argument("--step", type=int, default=DEFAULT_STEP_SECONDS)
    ap.add_argument("--no-verify", action="store_true")
    args = ap.parse_args()

    seed(args.vm_url, args.window_mins, args.step)
    # small settle so force_flush + latencyOffset (1s) make points queryable
    time.sleep(2)
    if args.no_verify:
        return 0
    return 0 if verify(args.vm_url, args.window_mins, args.step) else 1


if __name__ == "__main__":
    sys.exit(main())
